### ISSUE TITLE
You updated index page is not being published to your website.

### ISSUE THREAD

**Issue by jelkner** [SendMeBread/Websites#1]
I can see the changes you made to your index.html file in your repo, but it is not being published to your website.  Check the Pages settings to see if you can figure out why this is so.

**Comment by SendMeBread** [comment]
Understood, I have also noticed this. So far I have not figured this out, therefore manually re-publishing the index.html file. I will check it out again.

**Comment by SendMeBread** [comment]
It has been updated. I have not figured out a way to make it automated, but I won't be editing it until Monday anyway. Essentially you are now able to take a look at the "Finished" Website, I plan to eventually make this the whole periodic table.

**Comment by SendMeBread** [comment]
It is officially automatically building & deploying.
